{	"version": "b27B1",
    "contracts": {
		"SPY": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"XLP": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"LIT": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"XLU": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"XLV": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"TSLA": {
			"strategy": "Macd_Strat_3",
			"enabled": false,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"FXI": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"QQQ": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"GLD": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"SLV": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"USO": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"UNG": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
        "SMH": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"BOTZ": {
			"strategy": "Macd_Strat_3",
			"enabled": false,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"ITB": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"XBI": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"SVXY": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"UVXY": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"TLT": {
			"strategy": "Macd_Strat_3",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"TQQQ": {
			"strategy": "Macd_Strat_4",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"TNA": {
			"strategy": "Macd_Strat_4",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"UGL": {
			"strategy": "Macd_Strat_4",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"UCO": {
			"strategy": "Macd_Strat_4",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"FAS": {
			"strategy": "Macd_Strat_4",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"UPRO": {
			"strategy": "Macd_Strat_4",
			"enabled": true,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"UBOT": {
			"strategy": "Macd_Strat_4",
			"enabled": false,
			"sectype": "STK",
			"exchange": "SMART",
			"currency": "USD",
			"multiplier": 1,
			"margin": 1,
			"automargin": 0.3,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "NOT USED",
			"override": {
			}
		},
		"NQ": {
			"strategy": "Macd_Strat_1",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "GLOBEX",
			"currency": "USD",
			"multiplier": 20,
			"margin": 2534,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
			}
		},
		"CL": {
			"strategy": "Macd_Strat_1",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "NYMEX",
			"currency": "USD",
			"multiplier": 100,
			"margin": 2700,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202202",
			"override": {
			}
		},
		"ES": {
			"strategy": "Macd_Strat_1",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "GLOBEX",
			"currency": "USD",
			"multiplier": 50,
			"margin": 1994,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
			}
		},
		"YM": {
			"strategy": "Macd_Strat_1",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "ECBOT",
			"currency": "USD",
			"multiplier": 0.5,
			"margin": 1362,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202203",
			"override": {
			}
		},
		"NG": {
			"strategy": "Macd_Strat_1",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "NYMEX",
			"currency": "USD",
			"multiplier": 2500,
			"margin": 6949,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202202",
			"override": {
			}
		},
		"GC": {
			"strategy": "Macd_Strat_1",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "NYMEX",
			"currency": "USD",
			"multiplier": 10,
			"margin": 1161,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202202",
			"override": {
			}
		},
		"GE": {
			"strategy": "Macd_Strat_1",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "GLOBEX",
			"currency": "USD",
			"multiplier": 12500,
			"margin": 479,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202202",
			"override": {
			}
		},
		"SI": {
			"strategy": "Macd_Strat_1",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "NYMEX",
			"currency": "USD",
			"multiplier": 2500,
			"margin": 7484,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202203",
			"override": {
			}
		},
		"GBP": {
			"strategy": "Macd_Strat_1",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "GLOBEX",
			"currency": "USD",
			"multiplier": 62500,
			"margin": 5248,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202203",
			"override": {
			}
		},
		"ZB": {
			"strategy": "Macd_Strat_1",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "ECBOT",
			"currency": "USD",
			"multiplier": 1000,
			"margin": 8508,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202203",
			"override": {
			}
		},
		"ZN": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "ECBOT",
			"currency": "USD",
			"multiplier": 1000,
			"margin": 2123,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
						"size": 3
			}
		},
		"MNQ": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "GLOBEX",
			"currency": "USD",
			"multiplier": 2,
			"margin": 2436,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
					"size": 5
			}
		},
		"MES": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "GLOBEX",
			"currency": "USD",
			"multiplier": 5,
			"margin": 2050,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
					"size": 5
			}
		},
		"M2K": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "GLOBEX",
			"currency": "USD",
			"multiplier": 5,
			"margin": 1195,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
					"size": 5
			}
		},
		"MGC": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "NYMEX",
			"currency": "USD",
			"multiplier": 10,
			"margin": 1031,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
			}
		},
		"QI": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "NYMEX",
			"currency": "USD",
			"multiplier": 2500,
			"margin": 17851,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
					"size": 20
			}
		},
		"YI": {
			"strategy": "Macd_Strat_2",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "NYSELIFFE",
			"currency": "USD",
			"multiplier": 1000,
			"margin": 10843,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202209",
			"override": {
			}
		},
		"QM": {
			"strategy": "Macd_Strat_2",
			"enabled": false,
			"sectype": "FUT",
			"exchange": "NYMEX",
			"currency": "USD",
			"multiplier": 500,
			"margin": 4688,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202209",
			"override": {
			}
		},
		"MCL": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "NYMEX",
			"currency": "USD",
			"multiplier": 100,
			"margin": 2580,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
			}
		},
		"QG": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "NYMEX",
			"currency": "USD",
			"multiplier": 2500,
			"margin": 2205,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
			}
		},
		"M6E": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "GLOBEX",
			"currency": "USD",
			"multiplier": 12500,
			"margin": 544,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202212",
			"override": {
					"osc_ob": 80,
					"osc_os": 40,
					"osc_ob_exit": 85,
					"osc_os_exit": 35,
					"size": 3
			}
		},
		"10Y": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "ECBOT",
			"currency": "USD",
			"multiplier": 1000,
			"margin": 525,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202211",
			"override": {
					"osc_ob": 80,
					"osc_os": 40,
					"osc_ob_exit": 85,
					"osc_os_exit": 35,
					"size": 5

			}
		},
	    "MBT": {
			"strategy": "Macd_Strat_2",
			"enabled": true,
			"sectype": "FUT",
			"exchange": "CMECRYPTO",
			"currency": "USD",
			"multiplier": 0.1,
			"margin": 10873,
			"automargin": false,
			"leverage": 1,
			"commission": 5,
			"historical": true,
			"last_trade": "202211",
			"override": {
				"size": 10
			}
		},
		"EUR": {
			"strategy": "Macd_AtrTrail_M_Dual",
			"enabled": false,
			"sectype": "CASH",
			"exchange": "IDEALPRO",
			"currency": "USD",
			"multiplier": 20,	
			"margin": 1,
			"automargin": false,
			"leverage": 1,
			"commission": 0.005,
			"historical": true,
			"last_trade": "202104",	
			"override": {
			}
		}
	
    },
	
    "strategies": {
            "Macd_Strat_1": {
				"backtest":{
				    "base_strategy": "Macd_AtrTrail_M_Dual",
					"start_date": "2012-01-01",
		            "end_date" : "2022-09-29",
					"dual_data": true,
					"candle_size": "15 mins",
					"long_candle_size": "2 hours",
					"session_times": true,
					"session_start": "4:00",
					"session_end": "20:00",
					"cash": 20000,
					"buy_enabled": true,
					"sell_enabled": true,
					"close_enabled": true,
					"invert": false,
					"gain_close": false,
					"gain": 2,
					"take_profit_close": false,
					"take_profit": 1,
					"take_profit_threshold": 0.2,
					"stoploss_close": true,
					"stoploss": 2,
					"percentile_open": false,
					"percentile_close": false,
					"lowpercentile": 5,
					"highpercentile": 95,
					"percentile_period": 100,
				    "bb_open": false,
					"bb_close": false,
					"low_bb": 50,
					"high_bb": 50,
					"bb_period": 50,
					"dev_factor": 2,
					"macd_open": true,
					"macd_close": true,
					"macd1": 10,
					"macd2": 20,
					"macdsig": 7,
					"atr_close": true,
					"atrperiod": 14,
					"atrdist": 3,
					"trail_on_buy": false,
					"atrdist_trail": 0,
					"mean_return_close": false,
					"trend_open": true,
                    "trend_close": false,
					"trend": "STR",
					"trend_strength": 10,
					"smaperiod": 10,
					"dirperiod": 10,
                    "osc_open": true,
                    "osc_close": true,
					"oscillator": "MFI",
					"osc_period": 14,
					"osc_ob": 80,
					"osc_os": 40,
					"osc_ob_exit": 85,
					"osc_os_exit": 35,
					"size": 10,
					"percent_sizer": true
				},
				"optimize": {
					"lowpercentile": [3],
					"highpercentile": [97],
					"percentile_period" : [0],
					"macd1": [10],
					"macd2": [20],
					"macdsig": [7],
					"atrperiod": [14],
					"atrdist": [3,4],
					"trail_on_buy": [false],
					"atrdist_trail": [0],
					"smaperiod": [10],
					"dirperiod": [10],
					"oscillator": ["RSI"],
					"osc_period": [14],
					"osc_ob": [55,65,75,85,90],
					"osc_os": [25,45,55,65],
					"osc_ob_exit": [55,65,75,85,90],
					"osc_os_exit": [25,45,55,65]
				},
				"live": {
				    "base_strategy": "LiveBaseStrategy",
				    "client_Id": 8002,
				    "watchdog_market": "futures",
					"dual_data": true,
					"candle_size": "1 min",
					"long_candle_size": "15 mins",
					"buy_enabled": true,
					"sell_enabled": true,
					"close_enabled": true,
					"invert": false,
					"gain_close": true,
					"gain": 1,
					"take_profit_close": true,
					"take_profit": 0.2,
					"take_profit_threshold": 0.5,
					"stoploss_close": true,
					"stoploss": 1,
					"percentile_open": false,
					"percentile_close": false,
					"lowpercentile": 5,
					"highpercentile": 95,
					"percentile_period": 100,
				    "bb_open": false,
					"bb_close": false,
					"low_bb": 50,
					"high_bb": 50,
					"bb_period": 50,
					"dev_factor": 2,
					"macd_open": true,
					"macd_close": false,
					"macd1": 10,
					"macd2": 20,
					"macdsig": 7,
					"atr_close": false,
					"atrperiod": 14,
					"atrdist": 3,
					"trail_on_buy": false,
					"atrdist_trail": 0,
					"mean_return_close": false,
					"trend_open": true,
                    "trend_close": false,
					"trend": "STR",
					"trend_strength": 10,
					"smaperiod": 10,
					"dirperiod": 10,
                    "osc_open": true,
                    "osc_close": false,
					"oscillator": "MFI",
					"osc_period": 14,
					"osc_ob": 60,
					"osc_os": 50,
					"osc_ob_exit": 85,
					"osc_os_exit": 35,
					"size": 10,
					"percent_sizer": true
				}
			},
	        "Macd_Strat_2": {
				"backtest":{
				    "base_strategy": "Macd_AtrTrail_M_Dual",
					"start_date": "2020-03-14",
		            "end_date" : "2022-03-14",
					"dual_data": true,
					"candle_size": "15 mins",
					"long_candle_size": "4 hours",
					"session_times": true,
					"session_start": "4:00",
					"session_end": "20:00",
					"cash": 30000,
					"buy_enabled": true,
					"sell_enabled": true,
					"close_enabled": true,
					"invert": false,
					"gain_close": false,
					"gain": 2,
					"take_profit_close": false,
					"take_profit": 1,
					"stoploss_close": false,
					"stoploss": 60,
					"percentile_open": false,
					"percentile_close": false,
					"lowpercentile": 5,
					"highpercentile": 95,
					"percentile_period": 100,
				    "bb_open": false,
					"bb_close": false,
					"low_bb": 50,
					"high_bb": 50,
					"bb_period": 50,
					"dev_factor": 2,
					"macd_open": true,
					"macd_close": true,
					"macd1": 10,
					"macd2": 20,
					"macdsig": 7,
					"atr_close": true,
					"atrperiod": 14,
					"atrdist": 3,
					"trail_on_buy": false,
					"atrdist_trail": 0,
					"mean_return_close": false,
					"trend_open": true,
                    "trend_close": false,
					"trend": "DMI",
					"trend_strength": 10,
					"smaperiod": 10,
					"dirperiod": 10,
                    "osc_open": true,
                    "osc_close": true,
					"oscillator": "RSI",
					"osc_period": 14,
					"osc_ob": 60,
					"osc_os": 45,
					"osc_ob_exit": 65,
					"osc_os_exit": 40,
					"size": 10,
					"percent_sizer": true
				},
				"optimize": {
					"lowpercentile": [3],
					"highpercentile": [97],
					"percentile_period" : [0],
					"macd1": [10],
					"macd2": [20],
					"macdsig": [7],
					"atrperiod": [14],
					"atrdist": [3],
					"trail_on_buy": [false],
					"atrdist_trail": [0],
					"smaperiod": [10],
					"dirperiod": [10],
					"oscillator": ["MFI","RSI","STOCH"],
					"osc_period": [14],
					"osc_ob": [50,80,90],
					"osc_os": [25,40,60,80],
					"osc_ob_exit": [50,80,90],
					"osc_os_exit": [25,40,60,80]
				},
				"live": {
				    "base_strategy": "LiveBaseStrategy",
				    "client_Id": 8003,
				    "watchdog_market": "futures",
					"dual_data": true,
					"candle_size": "15 mins",
					"long_candle_size": "2 hours",
					"buy_enabled": true,
					"sell_enabled": true,
					"close_enabled": true,
					"invert": false,
					"gain_close": false,
					"gain": 1,
					"take_profit_close": true,
					"take_profit": 0.2,
					"take_profit_threshold": 0.5,
					"stoploss_close": false,
					"stoploss": 2,
					"percentile_open": false,
					"percentile_close": false,
					"lowpercentile": 5,
					"highpercentile": 95,
					"percentile_period": 100,
				    "bb_open": false,
					"bb_close": false,
					"low_bb": 50,
					"high_bb": 50,
					"bb_period": 50,
					"dev_factor": 2,
					"macd_open": true,
					"macd_close": true,
					"macd1": 10,
					"macd2": 20,
					"macdsig": 7,
					"atr_close": true,
					"atrperiod": 14,
					"atrdist": 3,
					"trail_on_buy": false,
					"atrdist_trail": 0,
					"mean_return_close": false,
					"trend_open": true,
                    "trend_close": false,
					"trend": "STR",
					"trend_strength": 10,
					"smaperiod": 10,
					"dirperiod": 10,
                    "osc_open": true,
                    "osc_close": true,
					"oscillator": "MFI",
					"osc_period": 14,
					"osc_ob": 60,
					"osc_os": 50,
					"osc_ob_exit": 85,
					"osc_os_exit": 35,
					"size": 10,
					"percent_sizer": true
				}
			},
		    "Macd_Strat_3": {
				"backtest":{
				    "base_strategy": "Macd_AtrTrail_M_Dual",
					"start_date": "2020-01-01",
		            "end_date" : "2022-09-29",
					"dual_data": true,
					"candle_size": "15 mins",
					"long_candle_size": "2 hours",
					"session_times": false,
					"session_start": "4:00",
					"session_end": "20:00",
					"cash": 30000,
					"buy_enabled": true,
					"sell_enabled": true,
					"close_enabled": true,
					"invert": false,
					"gain_close": false,
					"gain": 2,
					"take_profit_close": true,
					"take_profit": 0.5,
					"take_profit_threshold": 0.2,
					"stoploss_close": false,
					"stoploss": 2,
					"percentile_open": false,
					"percentile_close": false,
					"lowpercentile": 5,
					"highpercentile": 95,
					"percentile_period": 100,
				    "bb_open": false,
					"bb_close": false,
					"low_bb": 50,
					"high_bb": 50,
					"bb_period": 50,
					"dev_factor": 2,
					"macd_open": true,
					"macd_close": true,
					"macd1": 10,
					"macd2": 20,
					"macdsig": 7,
					"atr_close": true,
					"atrperiod": 14,
					"atrdist": 3,
					"trail_on_buy": false,
					"atrdist_trail": 0,
					"mean_return_close": false,
					"trend_open": true,
                    "trend_close": false,
					"trend": "STR",
					"trend_strength": 10,
					"smaperiod": 10,
					"dirperiod": 10,
                    "osc_open": true,
                    "osc_close": true,
					"oscillator": "MFI",
					"osc_period": 14,
					"osc_ob": 60,
					"osc_os": 50,
					"osc_ob_exit": 85,
					"osc_os_exit": 35,
					"size": 10,
					"percent_sizer": true
				},
				"optimize": {
					"lowpercentile": [3],
					"highpercentile": [97],
					"percentile_period" : [0],
					"macd1": [10],
					"macd2": [20],
					"macdsig": [7],
					"atrperiod": [14],
					"atrdist": [3],
					"trail_on_buy": [false],
					"atrdist_trail": [0],
					"smaperiod": [10],
					"dirperiod": [10],
					"oscillator": ["MFI","RSI","STOCH"],
					"osc_period": [14],
					"osc_ob": [60,70,80],
					"osc_os": [30,40,50],
					"osc_ob_exit": [65,75,85],
					"osc_os_exit": [35,45,55]
				},
				"live": {
				    "base_strategy": "LiveBaseStrategy",
				    "client_Id": 8004,
				    "watchdog_market": "stock",
					"dual_data": true,
					"candle_size": "15 mins",
					"long_candle_size": "2 hours",
					"buy_enabled": true,
					"sell_enabled": true,
					"close_enabled": true,
					"invert": false,
					"gain_close": false,
					"gain": 2,
					"take_profit_close": true,
					"take_profit": 0.2,
					"take_profit_threshold": 0.5,
					"stoploss_close": false,
					"stoploss": 2,
					"percentile_open": false,
					"percentile_close": false,
					"lowpercentile": 5,
					"highpercentile": 95,
					"percentile_period": 100,
				    "bb_open": false,
					"bb_close": false,
					"low_bb": 50,
					"high_bb": 50,
					"bb_period": 50,
					"dev_factor": 2,
					"macd_open": true,
					"macd_close": true,
					"macd1": 10,
					"macd2": 20,
					"macdsig": 7,
					"atr_close": true,
					"atrperiod": 14,
					"atrdist": 3,
					"trail_on_buy": false,
					"atrdist_trail": 0,
					"mean_return_close": false,
					"trend_open": true,
                    "trend_close": false,
					"trend": "STR",
					"trend_strength": 10,
					"smaperiod": 10,
					"dirperiod": 10,
                    "osc_open": true,
                    "osc_close": true,
					"oscillator": "MFI",
					"osc_period": 14,
					"osc_ob": 60,
					"osc_os": 50,
					"osc_ob_exit": 85,
					"osc_os_exit": 35,
					"size": 5,
					"percent_sizer": true
				}
			},
		    "Macd_Strat_4": {
				"backtest":{
				    "base_strategy": "Macd_AtrTrail_M_Dual",
					"start_date": "2020-10-18",
		            "end_date" : "2021-11-19",
					"dual_data": true,
					"candle_size": "15 mins",
					"long_candle_size": "4 hours",
					"session_times": true,
					"session_start": "4:00",
					"session_end": "20:00",
					"cash": 30000,
					"buy_enabled": true,
					"sell_enabled": true,
					"close_enabled": true,
					"invert": false,
					"gain_close": false,
					"gain": 2,
					"take_profit_close": false,
					"take_profit": 1,
					"stoploss_close": false,
					"stoploss": 60,
					"percentile_open": false,
					"percentile_close": false,
					"lowpercentile": 5,
					"highpercentile": 95,
					"percentile_period": 100,
				    "bb_open": false,
					"bb_close": false,
					"low_bb": 50,
					"high_bb": 50,
					"bb_period": 50,
					"dev_factor": 2,
					"macd_open": true,
					"macd_close": true,
					"macd1": 10,
					"macd2": 20,
					"macdsig": 7,
					"atr_close": true,
					"atrperiod": 14,
					"atrdist": 3,
					"trail_on_buy": false,
					"atrdist_trail": 0,
					"mean_return_close": false,
					"trend_open": true,
                    "trend_close": false,
					"trend": "DMI",
					"trend_strength": 10,
					"smaperiod": 7,
					"dirperiod": 10,
                    "osc_open": true,
                    "osc_close": true,
					"oscillator": "RSI",
					"osc_period": 14,
					"osc_ob": 60,
					"osc_os": 45,
					"osc_ob_exit": 65,
					"osc_os_exit": 40,
					"size": 20,
					"percent_sizer": true
				},
				"optimize": {
					"lowpercentile": [3],
					"highpercentile": [97],
					"percentile_period" : [0],
					"macd1": [10],
					"macd2": [20],
					"macdsig": [7],
					"atrperiod": [14],
					"atrdist": [1,2,3,4],
					"trail_on_buy": [false],
					"atrdist_trail": [0],
					"smaperiod": [10],
					"dirperiod": [10],
					"oscillator": ["MFI","RSI","STOCH"],
					"osc_period": [14],
					"osc_ob": [50,80,90],
					"osc_os": [40,60,80],
					"osc_ob_exit": [50,80,90],
					"osc_os_exit": [40,60,80]
				},
				"live": {
				    "base_strategy": "LiveBaseStrategy",
				    "client_Id": 8005,
				    "watchdog_market": "stock",
					"dual_data": true,
					"candle_size": "15 mins",
					"long_candle_size": "2 hours",
					"buy_enabled": true,
					"sell_enabled": true,
					"close_enabled": true,
					"invert": false,
					"gain_close": false,
					"gain": 2,
					"take_profit_close": true,
					"take_profit": 0.2,
					"take_profit_threshold": 0.5,
					"stoploss_close": false,
					"stoploss": 2,
					"percentile_open": false,
					"percentile_close": false,
					"lowpercentile": 5,
					"highpercentile": 95,
					"percentile_period": 100,
				    "bb_open": false,
					"bb_close": false,
					"low_bb": 50,
					"high_bb": 50,
					"bb_period": 50,
					"dev_factor": 2,
					"macd_open": true,
					"macd_close": true,
					"macd1": 10,
					"macd2": 20,
					"macdsig": 7,
					"atr_close": true,
					"atrperiod": 14,
					"atrdist": 3,
					"trail_on_buy": false,
					"atrdist_trail": 0,
					"mean_return_close": false,
					"trend_open": true,
                    "trend_close": false,
					"trend": "STR",
					"trend_strength": 10,
					"smaperiod": 10,
					"dirperiod": 10,
                    "osc_open": true,
                    "osc_close": true,
					"oscillator": "MFI",
					"osc_period": 14,
					"osc_ob": 60,
					"osc_os": 50,
					"osc_ob_exit": 85,
					"osc_os_exit": 35,
					"size": 5,
					"percent_sizer": true
				}
			}
    },
    "main": {
		"mode": "live",
		"offline": true,
		"timezone": "America/La_Paz",
        "debug": false
    },
    "connection": {
        "gateway_port": 7497,
        "gateway_ip": "127.0.0.1",
		"backtrader_client_number": 77,
		"ibapi_client_id": 99,
		"ib_insync_client_id": 79,
		"ib_insync_timeout": 500
    },
    "watchdog": {
        "enabled": true,
        "reset_time": ["06:02","18:02"],
        "live_test": 5,
        "cycle_mult": 2,
        "market": "futures",
        "early_trading": true,
        "late_trading": true,
        "gateway_version": 1015,
        "gateway_mode": false,
        "trading_mode": "paper",
        "connect_timeout": 120,
        "app_startup_time": 120,
        "app_timeout": 300,
        "retry_delay": 120
    },
	"data": {
		"json_output_dir": "./json/",
		"logs_output_dir": "./logs/",
		"results_output_dir": "./results/",
		"log_filename" : "logfile.log",
		"dataOutput": "./data/",
		"data_type": "TRADES",
		"max_days": true,
		"duration": "250 D",
		"data_retries": 10,
		"use_rth": 0,
		"update_margin": true,
		"data_provider": "ib_csv"
    },
    "analyzers": {
		"time_return": true,
		"trade": true,
		"sqn" : true,
		"sharpe_ratio": true,
		"positions_value": true,
		"draw_down": true,
		"cash_market": true,
		"ohlcv": true,
		"pyfolio": false,
		"live_plot": false
    },
    "observers": {
		"draw_down": true,
		"cash": false,
		"broker": true,
		"pnl": false
    },
    "display": {
        "enabled": false,
        "table": true,
        "one_plot": false,
        "plot_results": true,
        "writer": false
    },
	"telegram": {
		"enabled": false,
		"API_TOKEN": "1488106539:AAEyd94XhEL9HqZiCjexok-jS6IUFpjzPWg",
		"USER_ID": 470142411,
		"trade": true,
		"callback": false,
		"error": true
    }
}  